Entity linking eng
deepmipt/DeepPavlov pull request #1301
Opened 2020-08-18 19:52 UTC by dmitrijeuseew

Config for entity linking in English

2020-08-26 17:26 UTC, IgnatovFedor reviewed
Add entity_linking_eng to test_quick_start, add description to documentation

2020-08-26 17:26 UTC, IgnatovFedor commented on deeppavlov/models/kbqa/kbqa_entity_linking.py
> +    def link_entity(self, entity: str, context: str = None, template_found: str = None, cut_entity: bool = False) -> \
`variable: type = None` -> `varialbe: Optional[type] = None`

2020-08-26 17:26 UTC, IgnatovFedor commented on deeppavlov/models/kbqa/query_generator.py
> +                                                        entities_from_ner_batch, types_from_ner_batch):
```suggestion
                    entities_from_ner_batch, types_from_ner_batch):
```

2020-08-26 17:26 UTC, IgnatovFedor commented on deeppavlov/models/kbqa/query_generator.py
> +        confidence = 0.0
redundant declaration: you redeclare this variable two lines below

2020-08-26 17:26 UTC, IgnatovFedor commented on deeppavlov/models/kbqa/query_generator.py
>          log.debug(f"(query_parser)entity_combs: {entity_combs[:3]}, type_combs: {type_combs[:3]}, rel_combs: {rel_combs[:3]}")
```suggestion
        log.debug(f"(query_parser)entity_combs: {entity_combs[:3]}, type_combs: {type_combs[:3]},"
                  f" rel_combs: {rel_combs[:3]}")
```
too long line

2020-08-26 17:26 UTC, IgnatovFedor commented on deeppavlov/models/kbqa/query_generator.py
> +            candidate_outputs += [[rel for rel, score in combs[2][:-1]] + output + [confidence] for output in candidate_output]
```suggestion
            candidate_outputs += [[rel for rel, score in combs[2][:-1]] + output + [confidence]
                                  for output in candidate_output]
```
too long line

2020-08-26 17:26 UTC, IgnatovFedor commented on deeppavlov/models/kbqa/query_generator_online.py
> +                                                        entities_from_ner_batch, types_from_ner_batch):
```suggestion
                zip(question_batch, question_san_batch, template_type_batch,
                    entities_from_ner_batch, types_from_ner_batch):
```

2020-08-26 17:26 UTC, IgnatovFedor commented on deeppavlov/models/kbqa/query_generator_online.py
> +                                                            template_type, entities_from_ner, types_from_ner)
teplate_type: Expected type 'List[str]', got 'str' instead

2020-08-26 17:26 UTC, IgnatovFedor commented on deeppavlov/models/kbqa/query_generator_online.py
> +                                                                                    for output in candidate_output]
```suggestion
                                  for output in candidate_output]
```

2020-08-26 17:26 UTC, IgnatovFedor commented on deeppavlov/models/kbqa/tree_to_sparql.py
> +class AdjToNoun:
add to `docs/apiref/models/kbqa.rst`

2020-08-26 17:26 UTC, IgnatovFedor commented on deeppavlov/models/kbqa/tree_to_sparql.py
> +class UdpipeParser(Component):
add to `docs/apiref/models/kbqa.rst`

2020-08-27 08:13 UTC, IgnatovFedor requested changes

2020-08-27 08:13 UTC, IgnatovFedor commented on deeppavlov/models/kbqa/tree_to_sparql.py
> +                    or '``' in [nd.form for nd in elem.children]))))):
This is quite frightening. Could you decompose this condition into multiple `if`s or simplify it in other way? For example, `("«" in [nd.form for nd in elem.children] or '"' in [nd.form for nd in elem.children] or '``' in [nd.form for nd in elem.children])` could replaced with `{"«", '"', '``'} & {nd.form for nd in elem.children}`

2020-08-27 08:13 UTC, IgnatovFedor commented on deeppavlov/models/kbqa/tree_to_sparql.py
> +                    '``' not in [nd.form for nd in elem.children] or
same as comment on lines +297 to +300

2020-08-27 08:13 UTC, IgnatovFedor commented on deeppavlov/models/kbqa/tree_to_sparql.py
>                  log.debug(f"modifiers: {[modifier.form for modifier in modifiers]}")
comment on `["каким был", "какой была"]` from line 185: what if language is English?

2020-08-27 08:13 UTC, IgnatovFedor commented on deeppavlov/models/kbqa/tree_to_sparql.py
> +                        if (node.ord not in appos_token_nums or node.ord not in clause_token_nums)])
`clause_token_nums` haven't declared

2020-08-27 08:13 UTC, IgnatovFedor commented on deeppavlov/models/kbqa/tree_to_sparql.py
> +                    first_or_last = node_desc["amod"].intersection({"первый", "последний"})
what if language is English?

2020-08-27 10:50 UTC, dmitrijeuseew commented on deeppavlov/models/kbqa/query_generator_online.py
> +                log.debug(f"\n_______________________________\nfilled query: {filled_query}\n_______________________________\n")
I inserted it to make filled query more visible when debugging.

2020-08-27 11:04 UTC, dmitrijeuseew commented on deeppavlov/configs/kbqa/kbqa_cq_rus.json
> +        "freq_dict_filename": "{DOWNLOADS_PATH}/wikidata_rus/freqrnc2011.csv",
Loaded to share

2020-09-07 20:56 UTC, IgnatovFedor approved these changes

2020-09-07 20:56 UTC, merged