Grad accum
deepmipt/DeepPavlov pull request #1328
Opened 2020-10-09 17:41 UTC by dimakarp1996

Added gradient accumulation. Tested on SST-2.

2020-10-13 06:35 UTC, dilyararimovna requested changes

2020-10-13 06:35 UTC, dilyararimovna commented on deeppavlov/models/bert/bert_classifier.py
>          Args:
эти пустые строки в док стрингах не только для красоты, но и для корректной конвертации в readthedocs. верни все пустые строки на место

2020-10-13 06:35 UTC, dilyararimovna commented on deeppavlov/core/trainers/utils.py
>  from deeppavlov.core.common.metrics_registry import get_metric_by_name
верни пустую строку. здесь правила для импортов

2020-10-13 06:35 UTC, dilyararimovna commented on deeppavlov/core/trainers/utils.py
>  from deeppavlov.core.common.metrics_registry import get_metric_by_name
и дальше в файлах сделай правильный порядок импортов с пустыми строками

2020-10-13 06:35 UTC, dilyararimovna commented on deeppavlov/models/bert/bert_classifier.py
> +    def train_on_batch(self, features: List[InputFeatures], y: Union[List[int], List[List[int]]] = None) -> Dict:
ты добавляешь новую фичу для тренировки, при это я не вижу оставленной возможности тренировтаься как раньше. Должна быть проверка "что если использовать gradient accumulation, то одним образом тренировка, если не использовать, то другим способом.

2020-10-13 06:35 UTC, dilyararimovna commented on deeppavlov/models/bert/bert_ranker.py
>              predictions.append(pred[:, 1])
тут раньше была возможно вероятности или лейблы выдавать,сейчас только один вариант остался

2020-10-13 06:35 UTC, dilyararimovna commented on deeppavlov/core/trainers/nn_trainer.py
> +                 gradient_accumulation_steps: int = 1,
зачем? нигде не используется дальше в тренере

2020-10-13 08:54 UTC, dimakarp1996 commented on deeppavlov/models/bert/bert_ranker.py
>              predictions.append(pred[:, 1])
Вызывается функция суперкласса, у которого остаётся аргумент self.return_probas и который может сам выдавать вероятности или лейблы. Т.е ничего не пропало, а только перекочевало туда.

2020-10-13 08:55 UTC, dimakarp1996 commented on deeppavlov/models/bert/bert_classifier.py
> +    def train_on_batch(self, features: List[InputFeatures], y: Union[List[int], List[List[int]]] = None) -> Dict:
Fixed

2020-10-13 08:55 UTC, dimakarp1996 commented on deeppavlov/models/bert/bert_classifier.py
>          Args:
Вернул

2020-10-13 08:55 UTC, dimakarp1996 commented on deeppavlov/core/trainers/utils.py
>  from deeppavlov.core.common.metrics_registry import get_metric_by_name
здесь == где? В импорты пустые строки вернул

2020-10-13 08:55 UTC, dimakarp1996 commented on deeppavlov/core/trainers/nn_trainer.py
> +                 gradient_accumulation_steps: int = 1,
ок, убрал

2020-10-13 09:05 UTC, dilyararimovna requested changes
поправь код стайл - пробелов местами не хватает

2020-10-13 09:05 UTC, dilyararimovna commented on deeppavlov/models/bert/bert_ranker.py
>              predictions.append(pred[:, 1])
ок

2020-10-13 09:05 UTC, dilyararimovna commented on deeppavlov/models/bert/bert_classifier.py
> +    def train_on_batch(self, features: List[InputFeatures], y: Union[List[int], List[List[int]]] = None) -> Dict:
зачем делать две функции? мне кажется, проще код из train_on_batch_old перенести сюда

2020-10-13 09:58 UTC, dimakarp1996 commented on deeppavlov/core/trainers/utils.py
>  from deeppavlov.core.common.metrics_registry import get_metric_by_name
Ok

2020-10-13 09:59 UTC, dimakarp1996 commented on deeppavlov/models/bert/bert_classifier.py
> +import math
Ok

2020-10-14 16:46 UTC, yurakuratov requested changes
in addition to comments above:
- report results of testing on SST-2
- gradient accumulation is a very useful feature. It should be added not only to BERT classification models (check if it possible to move impl to TFModel)
- can you report checks that loss and gradients are equal in cases when gradient_accumulations_steps = 1 and gradient_accumulations_steps > 1 (they should be almost equal for large enough batches)
- add at least one test to check gradient_accumulation (test configuration file with enabled gradient accumulation)

2020-10-14 16:46 UTC, yurakuratov commented on deeppavlov/models/bert/bert_classifier.py
>              if self.optimizer is None:
What will happen if optimizer is specified?

2020-10-14 16:46 UTC, yurakuratov commented on deeppavlov/models/bert/bert_classifier.py
> -                self.train_op = tf.group(self.train_op, [self.global_step.assign(new_global_step)])
These lines should be used when `AdamWeightDecayOptimizer` is used.

2020-10-14 16:46 UTC, yurakuratov commented on deeppavlov/models/bert/bert_classifier.py
> -                self.train_op = self.get_train_op(self.loss, learning_rate=self.learning_rate_ph,
check get_train_op function implementation, you lose all features that are implemented in it by using raw optimizer

2020-10-14 16:46 UTC, yurakuratov commented on deeppavlov/models/bert/bert_classifier.py
> +        assert num_parts > 0
This could be checked in `__init__` method and raise exception in case of illegal values

2020-10-15 12:20 UTC, dimakarp1996 commented on deeppavlov/models/bert/bert_classifier.py
> -                self.train_op = tf.group(self.train_op, [self.global_step.assign(new_global_step)])
Ок

2020-10-15 12:20 UTC, dimakarp1996 commented on deeppavlov/models/bert/bert_classifier.py
>              if self.optimizer is None:
Ок

2020-10-15 12:20 UTC, dimakarp1996 commented on deeppavlov/models/bert/bert_classifier.py
> +        assert num_parts > 0
Ок

2020-10-15 12:20 UTC, dimakarp1996 commented on deeppavlov/models/bert/bert_classifier.py
> +    def split(self, features: List):
Ок

2020-10-15 12:28 UTC, dimakarp1996 commented
I am currently running testing on SST-2. Test config will be added. Check will be done manually. I doubt if it is possible to move implementation, as train_on_batch method is not defined in the base class and therefore has to be redefined in all subclasses.

2020-10-16 09:56 UTC, dimakarp1996 commented
1)Added two test configs
2)Metrics in a config without gradient accumulation:
{"train": {"eval_examples_count": 60614, "metrics": {"accuracy": 0.9889, "f1_macro": 0.9887}, "time_spent": "0:05:15"}}
{"valid": {"eval_examples_count": 6735, "metrics": {"accuracy": 0.9535, "f1_macro": 0.9528}, "time_spent": "0:00:35"}}
{"test": {"eval_examples_count": 872, "metrics": {"accuracy": 0.9278, "f1_macro": 0.9276}, "time_spent": "0:00:05"}}
Metrics in a config with gradient accumulation:
{"train": {"eval_examples_count": 60614, "metrics": {"accuracy": 0.9898, "f1_macro": 0.9897}, "time_spent": "0:05:06
{"valid": {"eval_examples_count": 6735, "metrics": {"accuracy": 0.9523, "f1_macro": 0.9516}, "time_spent": "0:00:34"
{"test": {"eval_examples_count": 872, "metrics": {"accuracy": 0.9243, "f1_macro": 0.9242}, "time_spent": "0:00:05"}}

2020-10-16 10:12 UTC, dimakarp1996 commented
No gradient accumulation(batch size 32):
{"train": {"eval_examples_count": 60614, "metrics": {"accuracy": 0.9889, "f1_macro": 0.9887}, "time_spent": "0:05:15"}}
{"valid": {"eval_examples_count": 6735, "metrics": {"accuracy": 0.9535, "f1_macro": 0.9528}, "time_spent": "0:00:35"}}
{"test": {"eval_examples_count": 872, "metrics": {"accuracy": 0.9278, "f1_macro": 0.9276}, "time_spent": "0:00:05"}}

2022-04-07 12:30 UTC, closed without merging