Feat/add russian super glue support
deepmipt/DeepPavlov pull request #1575
Opened 2022-06-27 06:47 UTC by vaskonov

Feat/add russian super glue support

2022-07-01 12:04 UTC, IgnatovFedor requested changes

2022-07-01 12:45 UTC, mtalimanchuk commented on docs/features/models/superglue.rst
> +`Russian SuperGlue <https://russiansuperglue.com/>`__ is a benchmark that contains a set of tasks in Russian developed for evaluating a general language understanding.
for evaluating general language understanding

2022-07-01 12:45 UTC, mtalimanchuk commented on docs/features/models/superglue.rst
> +`DaNetQA (Yes/no Question Answering Dataset for the Russian)` is a binary classification task of question answering, in which the model is asked to answer a yes/no question based on a given context f
for Russian

2022-07-01 12:45 UTC, mtalimanchuk commented on docs/features/models/superglue.rst
> +In `RWSD (The Russian Winograd Schema Challenge)` the data is a set of sentences that differ with one or two words
is a set of sentences that differ by one or two words

2022-07-02 13:08 UTC, vaskonov commented on tests/test_quick_start.py
> +    "russian_super_glue":{
parus test has been added

2022-07-02 13:17 UTC, vaskonov commented on deeppavlov/dataset_readers/huggingface_dataset_reader.py
> +def preprocess_wsc(dataset: Dataset) -> Dict[str, List[str]]:
added

2022-07-02 13:22 UTC, vaskonov commented on deeppavlov/dataset_readers/huggingface_dataset_reader.py
> +def preprocess_multirc(examples: Dataset, *, clean_paragraphs: bool = True) -> Dict[str, List[str]]:
done

2022-07-13 20:50 UTC, closed without merging